services:
  db:
    image: mongo:7
    ports:
      - 27017:27017
    volumes:
      - ./db/backup:/backup
      - ./db/data:/data/db # MongoDBのデータ永続化
    networks:
      - shirasagi_net

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - ./app/shirasagi:/var/www/shirasagi
      - ./app/shirasagi/public:/var/www/shirasagi/public
      - ./app/shirasagi/private:/var/www/shirasagi/private
    depends_on:
      - db
    networks:
      - shirasagi_net
    environment:
      #- VOICE_API_ENDPOINT=http://localhost
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    restart: always
    volumes:
      - ./app/shirasagi/:/var/www/shirasagi
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
    depends_on:
      - app
    networks:
      - shirasagi_net

networks:
  shirasagi_net:
    driver: bridge
