server {
   listen 80;
   server_name localhost;
   return 301 http://172.40.0.4$request_uri;
}

server {
   include conf.d/server/ss.conf;
   listen 80;
   server_name tst-shirasagi4.ssenv.web-tips.co.jp;
   root /var/www/shirasagi/public/sites/w/w/w/_/;
   access_log /var/log/nginx/access.log;
   error_log  /var/log/nginx/error.log;
}


