<<<<<<< HEAD
server {
   listen 80;
   server_name localhost;
   return 301 http://172.40.0.4$request_uri;
}

server {
   include conf.d/server/ss.conf;
   listen 80;
<<<<<<< HEAD
   server_name 172.20.0.4;
=======
server {
   listen 80;
   server_name localhost;
   return 301 http://172.20.0.4$request_uri;
}

server {
   include conf.d/server/ss.conf;
   listen 80;
<<<<<<< HEAD
   server_name localhost;
>>>>>>> 45c5c88 (feat: first commit)
=======
   server_name 172.20.0.4;
>>>>>>> 692e71f (fix: 読み上げ機能エラーの為固定IP化)
=======
   server_name tst-shirasagi4.ssenv.web-tips.co.jp;
>>>>>>> 5048064 (firstcommit)
   root /var/www/shirasagi/public/sites/w/w/w/_/;
   access_log /var/log/nginx/access.log;
   error_log  /var/log/nginx/error.log;
}


