upstream unicorn {
  server unix:/shirasagi/tmp/sockets/unicorn.sock;
}

server {
   include conf.d/server/ss.conf;
   listen 80;
   server_name localhost;
   root /shirasagi/public/sites/w/w/w/_/;
   access_log /var/log/nginx/access.log;
   error_log  /var/log/nginx/error.log;
}

